name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'auto-update'
      - 'patch'
      - 'fix'
      - 'chore'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  default: 'patch'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  - title: '⬆️ Upgrades & Patches'
    labels:
      - 'patch'
      - 'upgrades'
  - title: '🔒 Security Patches'
    labels:
      - 'security-patch'
      - 'security-fix'
  - title: '🤖 Automatic Updates'
    labels:
      - 'auto-update'
  - title: '📝 Documentation'
    labels:
      - 'chore'

autolabeler:
  - label: 'chore'
    files:
      - '*.md'

  - label: 'enhancement'
    title: '/enhancement/✨i'

  - label: 'bugfix'
    title: '/bugfix/i'

  - label: 'bug'
    title: '/🐛|🐞|fixes/i'

  - label: 'security-patch'
    title: '/🔒|security fix/i'

  - label: 'upgrades'
    title: '/⬆️|upgrade/i'

  - label: 'auto-update'
    title: '/🤖/i'

  - label: 'feature'
    title: '/🚀|🎉/i'

change-template: |
  <details>
    <summary>$TITLE @$AUTHOR (#$NUMBER)</summary>

    $BODY
  </details>

template: |
  ## Changes

  $CHANGES

